behaviors:
  CyberMan:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size:  2048
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.1
        use_actions: true
        demo_path: Demos/BasicTraining62.demo
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
    keep_checkpoints: 40
    max_steps: 25000000
    time_horizon: 128
    summary_freq: 25000
environment_parameters:
  Gamelevel:
    curriculum:
        - name: Level1
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 1.0
        - name: Level2
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 2.0
        - name: Level3
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 3.0
        - name: Level4
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 4.0
        - name: Level5
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 5.0
        - name: Level6
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 6.0
        - name: Level7
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 7.0
        - name: Level8
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 8.0
        - name: Level9
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 9.0
        - name: Level10
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 10.0
        - name: Level11
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 11.0
        - name: Level12
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 12.0
        - name: Level13
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 13.0
        - name: Level14
          completion_criteria: 
            measure: reward
            behavior: CyberMan
            signal_smoothing: true
            min_lesson_length: 600
            threshold: 0.825
          value: 14.0